LOCAL_PATH:= $(call my-dir)

include $(CLEAR_VARS)

LOCAL_SRC_FILES := \
	usniff.c \
	wireless.c

LOCAL_C_INCLUDES := \
	$(LOCAL_PATH)

LOCAL_NO_DEFAULT_COMPILER_FLAGS := true
LOCAL_C_INCLUDES += $(TARGET_PROJECT_INCLUDES) $(TARGET_C_INCLUDES)
LOCAL_CFLAGS := $(TARGET_GLOBAL_CFLAGS) $(PRIVATE_ARM_CFLAGS)

LOCAL_C_INCLUDES += external/netlink/include external/iw
LOCAL_CFLAGS += -Wall -Werror
LOCAL_SHARED_LIBRARIES += libnl

LOCAL_LDFLAGS := -Wl,--no-gc-sections
LOCAL_MODULE_PATH := $(TARGET_OUT_OPTIONAL_EXECUTABLES)
LOCAL_MODULE_TAGS := optional
LOCAL_MODULE := usniff

include $(BUILD_EXECUTABLE)

